const { findSourceMap } = require('module')
const {LListSet} = require('../../lib/setAndLinkedList.js')
//filling the lists
let firstList = new LListSet()
firstList.insertInOrder(20)
firstList.insertInOrder(10)
firstList.insertInOrder(5)
firstList.insertInOrder(50)
firstList.insertInOrder(1)
firstList.insertInOrder(30)
let secondList = new LListSet()
secondList.insertInOrder(20)
secondList.insertInOrder(5)
secondList.insertInOrder(30)
//testing the functions of the sets with the linked lists as storage
console.log('firstList is:')
firstList.display()
console.log('secondList is:')
secondList.display()
console.log('union of both lists:')
secondList.union(firstList)
console.log('intersection of both lists')
firstList.intersect(secondList)
console.log("the size of the set is:")
console.log(firstList.size())
console.log("is subset or not:")
console.log(secondList.subset(firstList))
console.log('difference between the lists')
firstList.difference(secondList)
console.log('findHigher: '+ secondList.findHigher(35))
console.log('firstLower: '+ firstList.findLower(10))